FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=dhruvika
ENV N8N_BASIC_AUTH_PASSWORD=Queen1234
ENV WEBHOOK_URL=https://latest-newz-blogger.onrender.com
ENV GENERIC_TIMEZONE=Asia/Kolkata
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=5678
ENV N8N_PROTOCOL=https
